package com.test.helloworld

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Controller
import org.springframework.web.bind.annotation.*


@Controller // This means that this class is a Controller
@RequestMapping(path = ["/demo"]) // This means URL's start with /demo (after Application path)
class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private val userRepository: NotabaristaRepository? = null

    @PostMapping(path = ["/add"]) // Map ONLY POST Requests
    @ResponseBody
    fun addNewUser(@RequestParam id: Int?
                   , @RequestParam name: String?): String {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        val n = Notabarista(id, name)

        userRepository?.save(n)
        return "Saved"
    }

    @GetMapping(path = ["/all"])
    @ResponseBody
    fun getAllUsers(): Iterable<Notabarista?>? {
        // This returns a JSON or XML with the users
        return userRepository!!.findAll()
    }
}